#TODO: replace main with the actual name

GAME := main
BINDIR := bin
GAMEDIR := $(addprefix $(BINDIR)/,$(GAME).exe)
SRCS := $(wildcard src/*/*.c) $(wildcard src/*/*/*.c) src/$(GAME).c
HEADERS := $(wildcard src/headers/*.h)
OBJDIR := build
OBJS := $(SRCS:src/%.c=$(OBJDIR)/%.o)

all: build
	@./bin/$(GAME)

proto1/dev-%: build
	@echo scenario: the very first prototype of the game
	@./bin/$(GAME) $@ placeholder

dev-%: build
	@./bin/$(GAME) $@

dev-flags:
	@echo "-fullscreen set the game in full screen mode"
	@echo "-fps show fps in the window"
	@echo "-limit_fps:X limit the fps to X" 




build: $(OBJS)
	@gcc \
	-std=c99 \
	$^ \
	-I ".\SDL\include" \
	-L ".\SDL\lib" \
	-l mingw32 \
	-l SDL2main \
	-l SDL2 \
	-l SDL2_ttf \
	-l SDL2_mixer \
	-l SDL2_image \
	-o $(GAMEDIR)


$(OBJDIR)/%.o: src/%.c $(HEADERS)
	@gcc -c -o $@ $<


clean:
	@rm -f build/*/*
	@rm -f build/$(GAME).o
	@rm -f bin/$(GAME).exe

count_lines:
	@find ./src -name *.h -o -name *.c | xargs wc -l


